version: "3"

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: /venv/bin/gunicorn yemake_react.wsgi --bind 0.0.0.0:8000
    volumes:
    - static_files:/backend/static_files #after static folder create - fill static_files volume
    - media:/backend/media #after static folder create - fill static_files volume
    ports:
      - "8000:8000"
#  frontend:
#    container_name: frontend
#    build:
#      context: ./frontend/gui
#      dockerfile: Dockerfile
#    volumes:
#      - build_folder:/frontend #"build" folder fills builder_folder
  nginx:
    image: nginx:latest
#    build:
#      context: ./nginx
#      dockerfile: Dockerfile
    container_name: nginx-proxy
    ports:
      - 80:80
    volumes:
      - ./frontend/gui/build:/var/www/frontend/build #nginx use filled "builder_folder"
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_files:/var/www/backend/static_files
      - media:/var/www/backend/media
    depends_on:
#      - frontend
      - backend
volumes:
  pgdata:
  static_files:
#  build_folder:
  media:
